[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "camelot>=12.6.29",
    "google-generativeai>=0.8.5",
    "langchain>=1.1.0",
    "pymupdf>=1.26.6",
    "python-dotenv>=1.2.1",
    "qdrant-client>=1.16.1",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
